- name: Install the admin node for kubernetes
  hosts: nodes
  become: yes
  remote_user: vagrant
  tasks:
  - name: Enroll the nodes
    shell: "kubeadm join 192.168.51.2:6443 --token a9eqcf.p712skks1hsd67dl  --discovery-token-ca-cert-hash sha256:6b93eb30331ddb8d377683c589f01842d9c0545830b9ee42bd073da7b22058cf"
