- name: Install the admin node for kubernetes
  hosts: nodes
  become: yes
  remote_user: vagrant
  tasks:
  - name: Enroll the nodes
    shell: "kubeadm join 192.168.51.2:6443 --token 6eju96.4jp0ic8898po5eon  --discovery-token-ca-cert-hash sha256:f674982da1d840fcdaaf15b5b2153150dd815c9e9f36df88bded7727b2f50b66"
