- name: Install the admin node for kubernetes
  hosts: nodes
  become: yes
  remote_user: vagrant
  tasks:
  - name: Enroll the nodes
    shell: "kubeadm join 192.168.51.2:6443 --token afq7xf.v2gxe7cm94b8hpkl  --discovery-token-ca-cert-hash sha256:66b11c1784e6350fe460b2e25af5425c3616152205b1acc0744b9c353c2fd5b6"
