- name: Install the admin node for kubernetes
  hosts: nodes
  become: yes
  remote_user: vagrant
  tasks:
  - name: Enroll the nodes
    shell: "kubeadm join 192.168.51.2:6443 --token 6ai33m.b2afflcgzyjsfwpn  --discovery-token-ca-cert-hash sha256:e06006f8b3c109bedbdd7eb3ff0b6323bcabdd9e7ec3d00fb1fcf05bb3178474"
