
- name: Install the admin node for kubernetes
  hosts: nodes
  become: yes
  remote_user: vagrant
  tasks:
  - name: Reset containerd
    shell: rm /etc/containerd/config.toml
    ignore_errors: yes
  - name: restart containerd
    systemd:
      name: containerd
      state: restarted
  - name: Enroll the nodes
    shell: "kubeadm join 192.168.51.2:6443 --token wuvbhj.a5gyjxggoyh8657c  --discovery-token-ca-cert-hash sha256:b6aa259f32e5c11d62b43b4bcb52aa8e43fb1fec5c546defaf87a926451f2636"
