---
all:
  vars:
    ansible_ssh_pass: vagrant
  children:
    management:
      hosts:
        manager1:
          ansible_port: 2222
          ansible_ssh_host: 127.0.0.1
    nodes:
      hosts:
        node1:
          ansible_port: 2200
          ansible_ssh_host: 127.0.0.1
        node2:
          ansible_port: 2201
          ansible_ssh_host: 127.0.0.1
        node3:
          ansible_port: 2202
          ansible_ssh_host: 127.0.0.1
        node4:
          ansible_port: 2203
          ansible_ssh_host: 127.0.0.1