---
all:
  vars:
    ansible_user: vagrant
    ansible_ssh_pass: vagrant
  children:
    management:
      hosts:
        - "192.168.51.2"
    nodes:
      hosts:
        - "192.168.51.3"
        - "192.168.51.4"
        - "192.168.51.5"
        - "192.168.51.6"