# ############### KUBERNETES MANAGER NODE ##############################################################################
- name: Install the admin node for kubernetes
  hosts: nodes
  become: yes
  remote_user: vagrant
  vars_files:
    - versions.yml
  roles:
    - { role: ubuntu-docker, tags: ["complete", "base"] }
    - { role: ubuntu-kubernetes-core, tags: ["complete", "base"] }
  pre_tasks:
  - name: Disable swap for current session
    command: swapoff -a
  - name: Set up the name of the managers and nodes for the cluster
    lineinfile:
      path: /etc/hosts
      line: "{{ item.ip }} {{ item.name }}"
    loop:
      "{{ managers }}"
  tasks:
  - name: Make sure this is the most up to date version
    apt:
      upgrade: yes
      update_cache: yes
  - name: Disable swap for current session
    command: swapoff -a
