# ############### KUBERNETES MANAGER NODE ##############################################################################
- name: Install the admin node for kubernetes
  hosts: management
  become: yes
  remote_user: vagrant
  vars_files:
    - versions.yml
  roles:
    - { role: ubuntu-docker, tags: ["complete", "base"] }
    - { role: ubuntu-kubernetes-core, tags: ["complete", "base"] }
    - { role: ubuntu-kubernetes-manager, tags: ["complete", "base"] }
    - { role: ubuntu-dev-master-config, tags: ["complete", "base"] }
  pre_tasks:
  - name: Disable swap for current session
    command: swapoff -a
  - name: Remove the graphical management systems
    apt:
      name: "{{ item }}"
      state: absent
    loop:
      - lightdm
      - gdm
  tasks:
  - name: Make sure this is the most up to date version
    apt:
      upgrade: yes
      update_cache: yes


