- name: Install the admin node for kubernetes
  hosts: management
  become: yes
  remote_user: vagrant
  tasks:
  - name: Copy over join grabber
    copy:
      src: "join-grabber.py"
      remote_src: no
      dest: "/root/join-grabber.py"
      mode: 0700
  - name: Grab the join string
    shell: python3 /root/join-grabber.py /root/initial_cluster.txt > /root/node-join-command.txt
  - name: Get the node-join-command
    fetch:
      src: /root/node-join-command.txt
      dest: /tmp/
