- name: Install the admin node for kubernetes
  hosts: management
  become: yes
  remote_user: vagrant
  tasks:
    - name: Install network components
      command: kubectl apply -f kube-flannel.yml
      args:
        chdir: /home/vagrant
      environment:
        SESSION_MANAGER: "local/kube-master:@/tmp/:ICE-unix/2345,unix/kube-master:/tmp/:ICE-unix/2345:"
        HOME: /home/vagrant
      become_user: vagrant
    - name: Install dashboard components
      command: "{{ item }}"
      args:
        chdir: /home/vagrant
      loop:
        - "kubectl apply -f dashboard.yaml"
        - "kubectl create serviceaccount dashboard-admin-sa"
        - "kubectl create clusterrolebinding dashboard-admin-sa --clusterrole=cluster-admin --serviceaccount=default:dashboard-admin-sa"
      environment:
        SESSION_MANAGER: "local/kube-master:@/tmp/:ICE-unix/2345,unix/kube-master:/tmp/:ICE-unix/2345:"
        HOME: /home/vagrant
      become_user: vagrant