---
- name: Install the main images needed for the master
  shell: kubeadm config images pull
- name: Initialize the kubernetes stack
  shell: "kubeadm init --ignore-preflight-errors=Swap --pod-network-cidr=10.0.0.0/8 --control-plane-endpoint={{ manager_url }}"
  register: output
- name: Get the tokens from the output.
  debug:
    var: output.stdout_lines
- name: Create folder at user home
  file:
    state: directory
    path: "/home/vagrant/.kube"
    owner: "vagrant"
    group: "vagrant"
- name: Copy over configuration
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "/home/vagrant/.kube/config"
    owner: "vagrant"
    group: "vagrant"
- name: Copy over custom calico configuration file
  copy:
    remote_src: no
    src: calico.yaml
    dest: /home/vagrant/calico_vagrant.yaml
