---
- name: Remove swap from the fstab entries
  lineinfile:
    state: absent
    path: /etc/fstab
    regexp: "swap"
- name: add Kubernetes apt-key for APT repository
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add Kubernetes APT repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'

- name: install kubernetes components
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - vim
    - git
    - curl
    - wget
    - kubelet
    - kubeadm
    - kubectl
    - etcd-client
- name: Create sysctl conf file for kubernetes
  file:
    state: touch
    path: /etc/sysctl.d/20-kubernetes.conf
- name: Set systemctl values
  lineinfile:
    path: /etc/sysctl.d/20-kubernetes.conf
    line: "{{ item }}"
    state: present
  loop:
    - "net.bridge.bridge-nf-call-ip6tables = 1"
    - "net.bridge.bridge-nf-call-iptables = 1"
    - "net.ipv4.ip_forward = 1"
- name: Reload systemctl
  shell: sysctl --system
#- name: Let containerd use the systemd namespace
#  lineinfile:
#    path: /etc/containerd/config.toml
#    line: "plugins.cri.systemd_cgroup = true"
#    state: present
- name: Create a configfile for kernel modules to load for containerd
  file:
    state: touch
    path: /etc/modules-load.d/containerd.conf
- name: Set module loads for containerd
  lineinfile:
    path: /etc/modules-load.d/containerd.conf
    line: "{{ item }}"
    state: present
  loop:
    - "overlay"
    - "br_netfilter"
- name: Set up the name of the managers and nodes for the cluster
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.name }}"
  loop:
    "{{ nodes }}"

- name: Add vagrant to the docker group
  user:
    name: vagrant
    groups:
      - docker
    append: yes
- name: Set the timezone
  community.general.timezone:
    name: "Pacific/Auckland"